version: "3"
services:
  mongo-db-container:
    image: mongo:latest
    container_name: "mongo-db-container"
    ports:
      - 27017:27017
    networks:
      - spring-boot-network
  springboot-mongodb:
    build: .
    container_name: springboot-mongodb
    ports:
      - 8084:8080
    networks:
      - spring-boot-network
networks:
  spring-boot-network: